=== WoltLab/WCF/XSD/fileDelete.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which delete files. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<xs:include schemaLocation="types.xsd" />
	
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="file" type="file" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="file">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="application" type="woltlab_varchar"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/fileDelete.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/6.0/fileDelete.xsd">
	<delete>
		<file>acp/js/WCF.ACP.Language.js</file>
		<file>acp/js/WCF.ACP.Language.min.js</file>
		<file>js/WCF.ImageViewer.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/Language/ItemList.js</file>
		<file>js/WoltLabSuite/Core/Ui/User/CoverPhoto/Delete.js</file>
		<file>js/WoltLabSuite/Core/Ui/User/CoverPhoto/Upload.js</file>
		<file>lib/form/AvatarEditForm.class.php</file>
		<file>lib/form/UserSearchForm.class.php</file>
		<file>lib/action/EmailValidationAction.class.php</file>
		<file>lib/action/UsernameValidationAction.class.php</file>
		<file>js/WoltLabSuite/Core/Acp/Controller/User/List.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Editor.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/Abstract.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/BanAction.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/DeleteAction.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/DisableAction.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/SendNewPasswordAction.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/ToggleConfirmEmailAction.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Ban.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Ban/Dialog.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Action/Handler/Delete.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Content/Remove/Clipboard.js</file>
		<file>js/WoltLabSuite/Core/Acp/Ui/User/Content/Remove/Handler.js</file>
		<file>js/WoltLabSuite/Core/Ui/User/Editor.js</file>
		<file>lib/acp/action/UserQuickSearchAction.class.php</file>
		<file>lib/acp/form/UserSearchForm.class.php</file>
		<file>lib/system/clipboard/action/UserClipboardAction.class.php</file>
		<file>lib/system/clipboard/action/UserContentClipboardAction.class.php</file>
		<file>lib/system/listView/user/UserSearchResultsListView.class.php</file>
		<file>lib/system/api/cuyz/valinor/qa/PHPStan/Stubs/Psr/SimpleCache/CacheInterface.stub</file>
		<file>lib/system/api/cuyz/valinor/src/Cache/ChainCache.php</file>
		<file>lib/system/api/cuyz/valinor/src/Cache/WarmupCache.php</file>
		<file>lib/system/api/cuyz/valinor/src/Definition/Repository/Cache/CacheClassDefinitionRepository.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Object/Factory/CacheObjectBuilderFactory.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Source/IdentifiableSource.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Builder/CasterNodeBuilder.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Builder/CasterProxyNodeBuilder.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Builder/IterableNodeBuilder.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Builder/StrictNodeBuilder.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Builder/TreeNode.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Builder/ValueAlteringNodeBuilder.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Exception/InvalidNodeHasNoMappedValue.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Exception/NoCasterForType.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Exception/SourceValueWasNotFilled.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/Node.php</file>
		<file>lib/system/api/cuyz/valinor/src/Mapper/Tree/NodeTraverser.php</file>
		<file>lib/system/api/cuyz/valinor/src/Normalizer/Formatter/StreamFormatter.php</file>
		<file>lib/system/api/cuyz/valinor/src/Normalizer/Transformer/EvaluatedTransformer.php</file>
		<file>lib/system/api/cuyz/valinor/src/Normalizer/Transformer/KeyTransformersHandler.php</file>
		<file>lib/system/api/cuyz/valinor/src/Normalizer/Transformer/ValueTransformersHandler.php</file>
		<file>lib/system/api/cuyz/valinor/src/Utility/Priority/HasPriority.php</file>
		<file>lib/system/api/cuyz/valinor/src/Utility/Priority/PrioritizedList.php</file>
		<file>lib/system/api/cuyz/valinor/src/Utility/PermissiveTypeFound.php</file>
		<file>lib/system/api/bin/pscss</file>
		<file>lib/system/api/scssphp/scssphp/bin/pscss</file>
		<file>lib/system/api/scssphp/scssphp/scss.inc.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Base/Range.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/AtRootBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/CallableBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/ContentBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/DirectiveBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/EachBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/ElseBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/ElseifBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/ForBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/IfBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/MediaBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/NestedPropertyBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Block/WhileBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Cache.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Compiler/CachedResult.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Compiler/Environment.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Exception/CompilerException.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Exception/ParserException.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Exception/RangeException.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Exception/ServerException.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Formatter.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Formatter/Compact.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Formatter/Compressed.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Formatter/Crunched.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Formatter/Debug.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Formatter/Expanded.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Formatter/Nested.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Formatter/OutputBlock.php</file>
		<file>lib/system/api/scssphp/scssphp/src/Parser.php</file>
		<file>lib/system/api/scssphp/scssphp/src/SourceMap/SourceMapGenerator.php</file>
		<file>lib/system/clipboard/action/ArticleClipboardAction.class.php</file>
		<file>lib/system/clipboard/action/TagClipboardAction.class.php</file>
		<file>lib/system/clipboard/action/ModerationQueueReportClipboardAction.class.php</file>
		<file>lib/system/clipboard/action/ModerationQueueClipboardAction.class.php</file>
		<file>lib/system/clipboard/action/ModerationQueueActivationClipboardAction.class.php</file>
		<file>lib/system/upload/AvatarUploadFileSaveStrategy.class.php</file>
		<file>lib/system/upload/AvatarUploadFileValidationStrategy.class.php</file>
		<file>lib/system/upload/UserCoverPhotoUploadFileSaveStrategy.class.php</file>
		<file>lib/system/upload/UserCoverPhotoUploadFileValidationStrategy.class.php</file>
		<file>lib/system/option/user/BirthdayUserOptionOutput.class.php</file>
		<file>lib/system/option/user/DateUserOptionOutput.class.php</file>
		<file>lib/system/option/user/FacebookUserOptionOutput.class.php</file>
		<file>lib/system/option/user/FloatUserOptionOutput.class.php</file>
		<file>lib/system/option/user/ImageUserOptionOutput.class.php</file>
		<file>lib/system/option/user/LabeledUrlUserOptionOutput.class.php</file>
		<file>lib/system/option/user/MessageUserOptionOutput.class.php</file>
		<file>lib/system/option/user/NewlineToBreakUserOptionOutput.class.php</file>
		<file>lib/system/option/user/SelectOptionsUserOptionOutput.class.php</file>
		<file>lib/system/option/user/TwitterUserOptionOutput.class.php</file>
		<file>lib/system/option/user/URLUserOptionOutput.class.php</file>
		<file>lib/system/option/user/UserOptionHandler.class.php</file>
		<file>lib/acp/form/UserOptionListForm.class.php</file>
		<file>lib/system/condition/UserOptionsCondition.class.php</file>
		<file>lib/acp/form/UserContentRevertChangesForm.class.php</file>

		<file>icon/font-awesome/v6/brands/42-group.svg</file>
		<file>icon/font-awesome/v6/brands/500px.svg</file>
		<file>icon/font-awesome/v6/brands/accessible-icon.svg</file>
		<file>icon/font-awesome/v6/brands/accusoft.svg</file>
		<file>icon/font-awesome/v6/brands/adn.svg</file>
		<file>icon/font-awesome/v6/brands/adversal.svg</file>
		<file>icon/font-awesome/v6/brands/affiliatetheme.svg</file>
		<file>icon/font-awesome/v6/brands/airbnb.svg</file>
		<file>icon/font-awesome/v6/brands/algolia.svg</file>
		<file>icon/font-awesome/v6/brands/alipay.svg</file>
		<file>icon/font-awesome/v6/brands/amazon-pay.svg</file>
		<file>icon/font-awesome/v6/brands/amazon.svg</file>
		<file>icon/font-awesome/v6/brands/amilia.svg</file>
		<file>icon/font-awesome/v6/brands/android.svg</file>
		<file>icon/font-awesome/v6/brands/angellist.svg</file>
		<file>icon/font-awesome/v6/brands/angrycreative.svg</file>
		<file>icon/font-awesome/v6/brands/angular.svg</file>
		<file>icon/font-awesome/v6/brands/app-store-ios.svg</file>
		<file>icon/font-awesome/v6/brands/app-store.svg</file>
		<file>icon/font-awesome/v6/brands/apper.svg</file>
		<file>icon/font-awesome/v6/brands/apple-pay.svg</file>
		<file>icon/font-awesome/v6/brands/apple.svg</file>
		<file>icon/font-awesome/v6/brands/artstation.svg</file>
		<file>icon/font-awesome/v6/brands/asymmetrik.svg</file>
		<file>icon/font-awesome/v6/brands/atlassian.svg</file>
		<file>icon/font-awesome/v6/brands/audible.svg</file>
