=== WoltLab/WCF/XSD/language.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install or update language items. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="language">
		<xs:complexType>
			 <xs:sequence>
				<xs:element name="category" type="category" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="languagecode" type="woltlab_varchar" use="required" />
			<xs:attribute name="languagename" type="woltlab_varchar" use="required" />
		</xs:complexType>
	</xs:element>
	
	<!-- language category element type -->
	<xs:complexType name="category">
		<xs:sequence>
			<xs:element name="item" type="item" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="woltlab_varchar" use="required" />
	</xs:complexType>
	
	<!-- language item element type -->
	<xs:complexType name="item" mixed="true">
		<xs:attribute name="name" type="woltlab_varchar" use="required" />
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/wcfsetup/setup/lang/setup_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<language xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/6.0/language.xsd" languagecode="en" languagename="English">
	<category name="wcf.global">
		<item name="wcf.global.title"><![CDATA[WoltLab Suite&trade; Installation]]></item>
		<item name="wcf.global.button.next"><![CDATA[Next »]]></item>
		<item name="wcf.global.progressBar"><![CDATA[{@$progress}% complete]]></item>
		<item name="wcf.global.welcome"><![CDATA[Thank you for choosing WoltLab Suite&trade;!]]></item>
		<item name="wcf.global.welcome.description"><![CDATA[This installer will help you to install <strong>WoltLab Suite&trade;</strong>.]]></item>
		<item name="wcf.global.welcome.language"><![CDATA[Language]]></item>
		<item name="wcf.global.welcome.language.description"><![CDATA[The installer language is currently set to {@$languageChooser}]]></item>
		<item name="wcf.global.welcome.language.change"><![CDATA[Change Language]]></item>
		<item name="wcf.global.license"><![CDATA[License Agreement]]></item>
		<item name="wcf.global.license.description"><![CDATA[Please read the following license agreement. Use the scroll bar to view the entire document.]]></item>
		<item name="wcf.global.license.accept.description"><![CDATA[Do you accept the terms and conditions of the license agreement? You may only install this software upon acceptance of the license agreement.]]></item>
		<item name="wcf.global.license.missingAcception"><![CDATA[You must accept the license agreement to continue this installation.]]></item>
		<item name="wcf.global.systemRequirements.required"><![CDATA[Required System Components]]></item>
		<item name="wcf.global.systemRequirements.recommended"><![CDATA[Recommended System Components]]></item>
		<item name="wcf.global.systemRequirements.element.required"><![CDATA[Required]]></item>
		<item name="wcf.global.systemRequirements.element.yours"><![CDATA[Found]]></item>
		<item name="wcf.global.systemRequirements.element.recommended"><![CDATA[Recommended]]></item>
		<item name="wcf.global.systemRequirements.php"><![CDATA[Installed version of the script-language “PHP”]]></item>
		<item name="wcf.global.systemRequirements.php.description"><![CDATA[The installed version of the script-language “PHP” is not within the range of supported versions.]]></item>
		<item name="wcf.global.systemRequirements.sql"><![CDATA[PDO Support]]></item>
		<item name="wcf.global.systemRequirements.sql.notFound"><![CDATA[not found]]></item>
		<item name="wcf.global.systemRequirements.sql.description"><![CDATA[The “pdo_mysql” PHP extension is required to install this software.]]></item>
		<item name="wcf.global.systemRequirements.uploadMaxFilesize"><![CDATA[Maximum Size for File Uploads]]></item>
		<item name="wcf.global.systemRequirements.uploadMaxFilesize.description"><![CDATA[The current configuration of the installed “PHP” version does not allow file uploads. Due to this configuration, some features of this software will not be available.]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary"><![CDATA[Graphics library]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary.requirement"><![CDATA[GD library or ImageMagick]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary.description"><![CDATA[A graphics library is needed to read images and for the dynamic image generation. The GD library or alternatively ImageMagick is required.]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary.notFound"><![CDATA[not found]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary.webp"><![CDATA[Support for WebP images missing]]></item>
		<item name="wcf.global.systemRequirements.active"><![CDATA[Enabled]]></item>
		<item name="wcf.global.systemRequirements.notActive"><![CDATA[Not enabled]]></item>
		<item name="wcf.global.systemRequirements.memoryLimit"><![CDATA[PHP memory limit]]></item>
		<item name="wcf.global.systemRequirements.memoryLimit.description"><![CDATA[The maximum available memory of PHP scripts is too low to properly run the software.]]></item>
		<item name="wcf.global.systemRequirements.openSSL"><![CDATA['OpenSSL' PHP extension]]></item>
		<item name="wcf.global.systemRequirements.openSSL.description"><![CDATA[Your PHP version has been compiled without OpenSSL support, it is required to establish secure connections.]]></item>
		<item name="wcf.global.systemRequirements.curl"><![CDATA['curl' PHP extension]]></item>
		<item name="wcf.global.systemRequirements.curl.description"><![CDATA[Your PHP version has been compiled without cURL support, outgoing connections might not be fully supported.]]></item>
		<item name="wcf.global.systemRequirements.hostname"><![CDATA[Host Name]]></item>
		<item name="wcf.global.systemRequirements.hostname.requirement"><![CDATA[Correct Host Name]]></item>
		<item name="wcf.global.systemRequirements.hostname.description"><![CDATA[The host name determined by the web server must match the host name within the web browser's URL bar.]]></item>
		<item name="wcf.global.systemRequirements.cookie"><![CDATA[Cookies]]></item>
		<item name="wcf.global.systemRequirements.cookie.description"><![CDATA[The web browser must send cookies back to the web server.]]></item>
		<item name="wcf.global.systemRequirements.tls"><![CDATA[Encrypted HTTPS Connection (SSL/TLS)]]></item>
		<item name="wcf.global.systemRequirements.tls.description"><![CDATA[The setup is accessed via an unencrypted HTTP connection. For privacy and security only encrypted HTTPS connections should be used. Unencrypted connections should be redirected to the encrypted variant. Some features might be unsupported when using unencrypted connections, as web browsers restrict some features for use with encrypted connections only.]]></item>
		<item name="wcf.global.systemRequirements.x64"><![CDATA[64-bit Support]]></item>
		<item name="wcf.global.systemRequirements.x64.description"><![CDATA[The PHP version must support 64-bit integers to correctly process numbers larger than ~2.1 billion.]]></item>
		<item name="wcf.global.next"><![CDATA[Loading next step …]]></item>
		<item name="wcf.global.next.description"><![CDATA[The installation is currently loading the next step, please wait.]]></item>
		<item name="wcf.global.configureDB"><![CDATA[Configure Database Access]]></item>
		<item name="wcf.global.configureDB.description"><![CDATA[The data for this software needs to be stored in a MySQL or MariaDB-database. Please enter your database access information!]]></item>
		<item name="wcf.global.configureDB.host"><![CDATA[Hostname]]></item>
		<item name="wcf.global.configureDB.user"><![CDATA[Username]]></item>
		<item name="wcf.global.configureDB.password"><![CDATA[Password]]></item>
		<item name="wcf.global.configureDB.database"><![CDATA[Database Name]]></item>
		<item name="wcf.global.configureDB.database.description"><![CDATA[The database must already exist.]]></item>
		<item name="wcf.global.configureDB.error"><![CDATA[An error has occurred while trying to connect to your database:
		<br><strong>{$exception->getMessage()}{if $exception->getPrevious()}<br>{$exception->getPrevious()->getMessage()}{/if}</strong>]]></item>
		<item name="wcf.global.configureDB.conflictedTables"><![CDATA[The following table{if $conflictedTables|count > 1}s{/if} already exist{if $conflictedTables|count == 1}s{/if} within your “{$dbName}” Database:<br>{implode from=$conflictedTables item="table"}{$table}{/implode}.<br><br>To solve this problem, please do one of the following:<br>1. Remove the table{if $conflictedTables|count > 1}s{/if} manually and continue the installation with the “Next” button or<br>2. You re-enter the database access information, but to a different database and continue the installation with the “Next” button.]]></item>
		<item name="wcf.global.createUser"><![CDATA[Create an Administrator]]></item>
		<item name="wcf.global.createUser.description"><![CDATA[The installation will now generate an administrator account for you. Please provide username, email address and password.]]></item>
		<item name="wcf.global.createUser.username"><![CDATA[Username]]></item>
		<item name="wcf.global.createUser.email"><![CDATA[Email Address]]></item>
		<item name="wcf.global.createUser.confirmEmail"><![CDATA[Confirm Email Address]]></item>
		<item name="wcf.global.createUser.password"><![CDATA[Password]]></item>
		<item name="wcf.global.createUser.confirmPassword"><![CDATA[Confirm Password]]></item>
		<item name="wcf.global.createUser.error"><![CDATA[Errors have occurred while registering the user account, please check the marked fields for errors.]]></item>
		<item name="wcf.global.createUser.error.empty"><![CDATA[This field can not be left empty.]]></item>
		<item name="wcf.global.createUser.error.username.invalid"><![CDATA[The username you have given is invalid. A valid username must be between 3 and 20 characters long.]]></item>
		<item name="wcf.global.createUser.error.email.invalid"><![CDATA[The email address you have given is invalid. A valid email address must be in the format of name@example.com]]></item>
		<item name="wcf.global.createUser.error.confirmEmail.notEqual"><![CDATA[The email addresses you have given are not identical. For security reasons, please make sure that both email address fields have been filled in and are identical.]]></item>
		<item name="wcf.global.createUser.error.confirmPassword.notEqual"><![CDATA[The passwords you have given are not identical. For security reasons, please make sure that both password fields have been filled in and are identical.]]></item>
		<item name="wcf.global.wcfDir.error"><![CDATA[An Error has accured while extracting the required files:
		<br><strong>{$exception->getMessage()}</strong><br>
		Please make sure that the destination folder exists and can be written to.]]></item>
	</category>
</language>

=== WoltLab/WCF/com.woltlab.wcf.notification/language/en.xml
<?xml version="1.0" encoding="UTF-8"?>
<language xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com/XSD/language.xsd" languagecode="en">
	<category name="wcf.user.notification">
		<item name="wcf.user.notification.title"><![CDATA[Notifications]]></item>
		<item name="wcf.user.notification.stats"><![CDATA[Overall {#$items} notification{if $items != 1}s{/if}]]></item>
		<item name="wcf.user.notification.noNotifications"><![CDATA[There are no notifications at the moment.]]></item>
		<item name="wcf.user.notification.icon"><![CDATA[Icon]]></item>
		<item name="wcf.user.notification.text"><![CDATA[Message]]></item>
		<item name="wcf.user.notification.time"><![CDATA[Time]]></item>
		<item name="wcf.user.notification.confirmAll"><![CDATA[Confirm all]]></item>
		<item name="wcf.user.notification.settings"><![CDATA[Notification settings]]></item>
		<item name="wcf.user.notification.settings.saved"><![CDATA[The settings were successfully saved.]]></item>
		<item name="wcf.user.notification.location.settings"><![CDATA[Notification settings]]></item>
		<item name="wcf.user.notification.location.overview"><![CDATA[Notification overview]]></item>
		<item name="wcf.user.notification.type.userMessages"><![CDATA[Infobox]]></item>
		<item name="wcf.user.notification.type.userMessages.title"><![CDATA[You have the following new notifications:]]></item>
		<item name="wcf.user.notification.type.mail"><![CDATA[E-Mail]]></item>
		<item name="wcf.user.notification.type.mail.subject"><![CDATA[{@$title}]]></item>
		<item name="wcf.user.notification.type.mail.footer"><![CDATA[


You can change your personal notification settings on {lang}{@PAGE_TITLE}{/lang} under the following URL:
{@$pageURL}index.php?form=UserNotificationSettings
If you do not want to recevive this mail notification in future just follow this link: {@$pageURL}index.php?action=NotificationDisable&notificationID={@$notification->notificationID}&userID={@$user->userID}&token={@$token}

]]></item>
		<item name="wcf.user.notification.type.mail.disabled"><![CDATA[You have disabled the mail notification successfully. You can reactive this notification in your profile settings at any time.]]></item>
		<item name="wcf.user.notification.feed"><![CDATA[Newest notifications]]></item>
		<item name="wcf.user.notification.feed.title"><![CDATA[Subcribe to notifications]]></item>
		<item name="wcf.user.notification.feed.description"><![CDATA[Your newest notifications on "{lang}{PAGE_TITLE}{/lang}"]]></item>
		<item name="wcf.user.notification.error.alreadyAccepted"><![CDATA[You have already confirmed this notification.]]></item>
		<item name="wcf.user.notification.object.type.void"><![CDATA[General]]></item>
	</category>
	<category name="wcf.user.usercp">
		<item name="wcf.user.usercp.menu.link.settings.notification"><![CDATA[Notifications]]></item>
		<item name="wcf.user.usercp.menu.link.management.notification"><![CDATA[Notifications]]></item>
	</category>
	<category name="wcf.header.userMenu">
		<item name="wcf.header.userMenu.userNotifications"><![CDATA[Notifications]]></item>
	</category>
	<category name="wcf.acp.option">
		<item name="wcf.acp.option.module_user_notification"><![CDATA[Notifications]]></item>
		<item name="wcf.acp.option.module_user_notification.description"><![CDATA[Activates the user notification system.]]></item>
		<item name="wcf.acp.option.category.user.notification"><![CDATA[Notifications]]></item>
		<item name="wcf.acp.option.category.user.notification.description"><![CDATA[]]></item>
		<item name="wcf.acp.option.category.user.notification.general"><![CDATA[General]]></item>
		<item name="wcf.acp.option.category.user.notification.general.description"><![CDATA[]]></item>
		<item name="wcf.acp.option.user_notification_user_menu_link_active"><![CDATA[Show user menu link]]></item>
		<item name="wcf.acp.option.user_notification_user_menu_link_active.description"><![CDATA[If this option is activated, a link to the user notification overview will be displayed in each user's user panel.]]></item>
		<item name="wcf.acp.option.user_notification_user_menu_link_autorefresh"><![CDATA[Automatic user menu link refresh]]></item>
		<item name="wcf.acp.option.user_notification_user_menu_link_autorefresh.description"><![CDATA[If this option is activated, the user menu link will refresh itself automatically using AJAX. This feature increases the server load.]]></item>
		<item name="wcf.acp.option.user_notification_user_menu_link_autorefresh_intervall"><![CDATA[Refresh intervall [Seconds]]]></item>
		<item name="wcf.acp.option.user_notification_user_menu_link_autorefresh_intervall.description"><![CDATA[How often shall the link refresh itself?]]></item>
		<item name="wcf.acp.option.user_notification_lifetime"><![CDATA[Lifetime of confirmed notifications [Hours]]]></item>
		<item name="wcf.acp.option.user_notification_lifetime.description"><![CDATA[Enter for how many hours confirmed notifications should be kept before deletion. -1 deactivates the automatic deletion of old confirmed notifications.]]></item>
		<item name="wcf.acp.option.user_notification_lifetime_unconfirmed"><![CDATA[Lifetime of unconfirmed notifications [Hours]]]></item>
		<item name="wcf.acp.option.user_notification_lifetime_unconfirmed.description"><![CDATA[Enter for how many hours unconfirmed notifications should be kept before deletion. 0 deactivates the automatic deletion of notifications.]]></item>
	</category>
	<category name="wcf.acp.package">
		<item name="wcf.acp.package.step.install.NotificationObjectTypePackageInstallationPlugin"><![CDATA[Installing notification objects ...]]></item>
		<item name="wcf.acp.package.step.uninstall.NotificationObjectTypePackageInstallationPlugin"><![CDATA[Uninstalling notification objects ...]]></item>
		<item name="wcf.acp.package.step.update.NotificationObjectTypePackageInstallationPlugin"><![CDATA[Updating notification objects ...]]></item>
		<item name="wcf.acp.package.step.install.NotificationTypePackageInstallationPlugin"><![CDATA[Installing notification types ...]]></item>
		<item name="wcf.acp.package.step.uninstall.NotificationTypePackageInstallationPlugin"><![CDATA[Uninstalling notification types ...]]></item>
		<item name="wcf.acp.package.step.update.NotificationTypePackageInstallationPlugin"><![CDATA[Updating notification types ...]]></item>
		<item name="wcf.acp.package.step.install.NotificationEventPackageInstallationPlugin"><![CDATA[Installing notification events ...]]></item>
		<item name="wcf.acp.package.step.uninstall.NotificationEventPackageInstallationPlugin"><![CDATA[Uninstalling notification events ...]]></item>
		<item name="wcf.acp.package.step.update.NotificationEventPackageInstallationPlugin"><![CDATA[Updating notification events ...]]></item>
	</category>
</language>
