=== WoltLab/WCF/XSD/menuItem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is used for xml-files which install, update or delete pages. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="item" type="item_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="item" type="item_delete" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- deleted menu item -->
	<xs:complexType name="item_delete">
		<xs:attribute name="identifier" type="woltlab_varchar" use="required" />
	</xs:complexType>
	
	<!-- imported/updated menu item -->
	<xs:complexType name="item_import">
		<xs:complexContent>
			<xs:extension base="item_delete">
				<xs:choice maxOccurs="unbounded">
					<xs:element name="title" type="title_element" minOccurs="1" maxOccurs="unbounded" />
					<xs:element name="menu" type="woltlab_varchar" minOccurs="1" maxOccurs="1" />
					<xs:element name="page" type="woltlab_varchar" minOccurs="1" maxOccurs="1" />
					<xs:element name="parent" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="externalURL" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="urlParameters" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- title element -->
	<xs:complexType name="title_element">
		<xs:simpleContent>
			<xs:extension base="woltlab_varchar">
				<xs:attribute name="language" type="woltlab_varchar" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/menuItem.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/6.0/menuItem.xsd">
	<import>
		<item identifier="com.woltlab.wcf.Dashboard">
			<menu>com.woltlab.wcf.MainMenu</menu>
			<title language="de">Dashboard</title>
			<title language="en">Dashboard</title>
			<page>com.woltlab.wcf.Dashboard</page>
		</item>
		<item identifier="com.woltlab.wcf.ArticleList">
			<menu>com.woltlab.wcf.MainMenu</menu>
			<title language="de">Artikel</title>
			<title language="en">Articles</title>
			<page>com.woltlab.wcf.ArticleList</page>
		</item>
		<item identifier="com.woltlab.wcf.UnreadArticleList">
			<parent>com.woltlab.wcf.ArticleList</parent>
			<title language="de">Ungelesene Artikel</title>
			<title language="en">Unread Articles</title>
			<page>com.woltlab.wcf.UnreadArticleList</page>
		</item>
		<item identifier="com.woltlab.wcf.WatchedArticleList">
			<parent>com.woltlab.wcf.ArticleList</parent>
			<title language="de">Abonnierte Artikel</title>
			<title language="en">Subscribed Articles</title>
			<page>com.woltlab.wcf.WatchedArticleList</page>
		</item>
		<item identifier="com.woltlab.wcf.MembersList">
			<menu>com.woltlab.wcf.MainMenu</menu>
			<title language="de">Mitglieder</title>
			<title language="en">Members</title>
			<page>com.woltlab.wcf.MembersList</page>
		</item>
		<item identifier="com.woltlab.wcf.RecentActivityList">
			<parent>com.woltlab.wcf.MembersList</parent>
			<title language="de">Letzte Aktivitäten</title>
			<title language="en">Recent Activity</title>
			<page>com.woltlab.wcf.RecentActivityList</page>
		</item>
		<item identifier="com.woltlab.wcf.UsersOnlineList">
			<parent>com.woltlab.wcf.MembersList</parent>
			<title language="de">Benutzer online</title>
			<title language="en">Users Online</title>
			<page>com.woltlab.wcf.UsersOnlineList</page>
		</item>
		<item identifier="com.woltlab.wcf.Team">
			<parent>com.woltlab.wcf.MembersList</parent>
			<title language="de">Team</title>
			<title language="en">Staff</title>
			<page>com.woltlab.wcf.Team</page>
		</item>
		<item identifier="com.woltlab.wcf.PrivacyPolicy">
			<menu>com.woltlab.wcf.FooterMenu</menu>
			<title language="de">Datenschutzerklärung</title>
			<title language="en">Privacy Policy</title>
			<page>com.woltlab.wcf.PrivacyPolicy</page>
		</item>
		<item identifier="com.woltlab.wcf.Contact">
			<menu>com.woltlab.wcf.FooterMenu</menu>
			<title language="de">Kontakt</title>
			<title language="en">Contact</title>
			<page>com.woltlab.wcf.Contact</page>
		</item>
	</import>
</data>
