=== WoltLab/WCF/XSD/objectType.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete user group options. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="type" type="type_import" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- import element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="type" type="type_delete" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- import element type -->
	<xs:complexType name="type_import">
		<xs:all>
			<xs:element name="name" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="definitionname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="classname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="category" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="categoryname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="points" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="listclassname" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="languagevariable" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="controller" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="allowcontent" type="woltlab_boolean" minOccurs="0" />
			<xs:element name="allowsidebar" type="woltlab_boolean" minOccurs="0" />
			<xs:element name="nicevalue" type="xs:integer" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<!-- delete element type -->
	<xs:complexType name="type_delete">
		<xs:all>
			<xs:element name="name" type="woltlab_varchar_nullable" minOccurs="0" />
			<xs:element name="definitionname" type="woltlab_varchar_nullable" minOccurs="0" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/objectType.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/6.0/objectType.xsd">
	<import>
		<!-- clipboard items -->
		<type>
			<name>com.woltlab.wcf.media</name>
			<definitionname>com.woltlab.wcf.clipboardItem</definitionname>
			<listclassname>wcf\data\media\ViewableMediaList</listclassname>
		</type>
		<!-- /clipboard items -->
		<!-- articles -->
		<type>
			<name>com.woltlab.wcf.article.category</name>
			<definitionname>com.woltlab.wcf.category</definitionname>
			<classname>wcf\system\category\ArticleCategoryType</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article.category</name>
			<definitionname>com.woltlab.wcf.acl</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.tagging.taggableObject</definitionname>
			<classname>wcf\system\tagging\TaggableArticle</classname>
			<options>module_article</options>
		</type>
		<type>
			<name>com.woltlab.wcf.likeableArticle</name>
			<definitionname>com.woltlab.wcf.like.likeableObject</definitionname>
			<classname>wcf\data\article\LikeableArticleProvider</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.likeableArticle.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\LikeableArticleUserActivityEvent</classname>
			<supportsReactions>1</supportsReactions>
		</type>
		<type>
			<name>com.woltlab.wcf.articleComment.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\ArticleCommentUserActivityEvent</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.articleComment.response.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\ArticleCommentResponseUserActivityEvent</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.searchableObjectType</definitionname>
			<classname>wcf\system\search\ArticleSearch</classname>
			<searchindex>wcf1_article_search_index</searchindex>
		</type>
		<type>
			<name>com.woltlab.wcf.article.content</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
			<enableToc>1</enableToc>
		</type>
		<type>
			<name>com.woltlab.wcf.article.content</name>
			<definitionname>com.woltlab.wcf.message.quote</definitionname>
			<classname>wcf\system\message\quote\ArticleContentMessageQuoteHandler</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.label.object</definitionname>
			<classname>wcf\system\label\object\ArticleLabelObjectHandler</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article.category</name>
			<definitionname>com.woltlab.wcf.label.objectType</definitionname>
			<classname>wcf\system\label\object\type\ArticleCategoryLabelObjectTypeHandler</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article.comment</name>
			<definitionname>com.woltlab.wcf.article.discussionProvider</definitionname>
			<classname>wcf\system\article\discussion\CommentArticleDiscussionProvider</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.articleComment.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\ArticleCommentUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.page</category>
		</type>
		<type>
			<name>com.woltlab.wcf.articleComment.response.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\ArticleCommentResponseUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.page</category>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.moderation.report</definitionname>
			<classname>wcf\system\moderation\queue\report\ArticleModerationQueueReportHandler</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article.category</name>
			<definitionname>com.woltlab.wcf.user.objectWatch</definitionname>
			<classname>wcf\system\user\object\watch\ArticleCategoryUserObjectWatch</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\ArticleUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.page</category>
		</type>
		<type>
			<name>com.woltlab.wcf.likeableArticle.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\LikeUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.page</category>
		</type>
		<type>
			<name>com.woltlab.wcf.articleComment.like.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\LikeUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.page</category>
			<supportsReactions>1</supportsReactions>
		</type>
		<type>
			<name>com.woltlab.wcf.articleComment.response.like.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\LikeUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.page</category>
			<supportsReactions>1</supportsReactions>
		</type>
		<type>
			<name>com.woltlab.wcf.article.recentActivityEvent</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\ArticleUserActivityEvent</classname>
		</type>
		<!-- /articles -->
		<type>
			<name>com.woltlab.wcf.page.content</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.box.content</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.user.aboutMe</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.user.signature</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
			<disallowedBBCodesPermission>user.signature.disallowedBBCodes</disallowedBBCodesPermission>
		</type>
		<type>
			<name>com.woltlab.wcf.genericFormOption</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.user.signature</name>
			<definitionname>com.woltlab.wcf.attachment.objectType</definitionname>
			<classname>wcf\system\attachment\SignatureAttachmentObjectType</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article</name>
			<definitionname>com.woltlab.wcf.attachment.objectType</definitionname>
			<classname>wcf\system\attachment\ArticleAttachmentObjectType</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.article.content</name>
			<definitionname>com.woltlab.wcf.attachment.objectType</definitionname>
			<classname>wcf\system\attachment\ArticleAttachmentObjectType</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.comment</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
			<disallowedBBCodesPermission>user.comment.disallowedBBCodes</disallowedBBCodesPermission>
		</type>
		<type>
			<name>com.woltlab.wcf.comment.response</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
			<disallowedBBCodesPermission>user.comment.disallowedBBCodes</disallowedBBCodesPermission>
		</type>
		<type>
			<name>com.woltlab.wcf.paidSubscription</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.user.option.generic</name>
			<definitionname>com.woltlab.wcf.message</definitionname>
		</type>
		<type>
			<name>com.woltlab.wcf.page</name>
			<definitionname>com.woltlab.wcf.searchableObjectType</definitionname>
			<classname>wcf\system\search\PageSearch</classname>
			<searchindex>wcf1_page_search_index</searchindex>
		</type>
		<type>
			<name>com.woltlab.wcf.bbcode.smiley</name>
			<definitionname>com.woltlab.wcf.category</definitionname>
			<classname>wcf\system\category\SmileyCategoryType</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.user.follow</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\UserFollowUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.user</category>
		</type>
		<type>
			<name>com.woltlab.wcf.user.registration.notification</name>
			<definitionname>com.woltlab.wcf.notification.objectType</definitionname>
			<classname>wcf\system\user\notification\object\type\UserRegistrationUserNotificationObjectType</classname>
			<category>com.woltlab.wcf.administration</category>
		</type>
		<type>
			<name>com.woltlab.wcf.user.recentActivityEvent.follow</name>
			<definitionname>com.woltlab.wcf.user.recentActivityEvent</definitionname>
			<classname>wcf\system\user\activity\event\FollowUserActivityEvent</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.user</name>
			<definitionname>com.woltlab.wcf.moderation.report</definitionname>
			<classname>wcf\system\moderation\queue\report\UserModerationQueueReportHandler</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.contact</name>
			<definitionname>com.woltlab.wcf.attachment.objectType</definitionname>
			<classname>wcf\system\attachment\ContactAttachmentObjectType</classname>
		</type>
		<type>
			<name>com.woltlab.wcf.contact.form</name>
			<definitionname>com.woltlab.wcf.file</definitionname>
			<classname>wcf\system\file\processor\ContactFormFileProcessor</classname>
		</type>
		<!-- page -->
		<type>
