=== WoltLab/WCF/XSD/spiderList.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />

	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="spider" type="spider" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- spider element type -->
	<xs:complexType name="spider">
		<xs:attribute name="ident" type="woltlab_varchar" />
		<xs:complexContent>
			<xs:all>
				<xs:element name="name" type="woltlab_varchar" minOccurs="1" />
				<xs:element name="url" type="woltlab_varchar" minOccurs="0" />
			</xs:all>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/spiderList/spiderList.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/6.0/spiderList.xsd">
	<spider ident="ABCdatos">
		<name>ABCdatos BotLink</name>
		<url>http://www.robotstxt.org/db/abcdatos.html</url>
	</spider>
	<spider ident="AbraveSpider">
		<name>Abrave</name>
		<url>http://robot.abrave.co.uk/</url>
	</spider>
	<spider ident="Accelatech RSSCrawler">
		<name>Accelatech</name>
	</spider>
	<spider ident="Accoona-AI-Agent">
		<name>Accoona</name>
		<url>https://www.accoona.com/about/</url>
	</spider>
	<spider ident="aconon Index">
		<name>aconon Index (raubfische.de)</name>
	</spider>
	<spider ident="AcoonBot">
		<name>Acoon</name>
		<url>http://www.acoon.de/robot.asp</url>
	</spider>
	<spider ident="Ahoy!">
		<name>Ahoy!</name>
		<url>http://www.robotstxt.org/db/ahoythehomepagefinder.html</url>
	</spider>
	<spider ident="AhrefsBot">
		<name>Ahrefs</name>
		<url>http://ahrefs.com/robot/</url>
	</spider>
	<spider ident="AlkalineBOT">
		<name>Alkaline</name>
		<url>http://www.robotstxt.org/db/Alkaline.html</url>
	</spider>
	<spider ident="Amazonbot">
		<name>Amazonbot</name>
		<url>https://developer.amazon.com/support/amazonbot</url>
	</spider>
	<spider ident="AlexaBOT">
		<name>Alexa</name>
		<url>http://www.alexa.com/help/webmasters</url>
	</spider>
	<spider ident="http://www.almaden.ibm.com/cs/crawler">
		<name>Almaden Crawler</name>
		<url>http://www.almaden.ibm.com/cs/crawler/</url>
	</spider>
	<spider ident="Barkrowler">
		<name>Barkrowler</name>
		<url>https://www.babbar.tech/crawler</url>
	</spider>
	<spider ident="EMC Spider">
		<name>ananzi</name>
	</spider>
	<spider ident="Anthill">
		<name>Anthill</name>
		<url>http://www.robotstxt.org/db/anthill.html</url>
	</spider>
	<spider ident="Aport">
		<name>Aport</name>
		<url>http://www.aport.ru/</url>
	</spider>
	<spider ident="AppleSyndication">
		<name>Apple</name>
	</spider>
	<spider ident="Applebot">
		<name>Applebot</name>
		<url>https://support.apple.com/en-gb/HT204683</url>
	</spider>
	<spider ident="Arachnophilia">
		<name>Arachnophilia</name>
		<url>http://www.robotstxt.org/db/arachnophilia.html</url>
	</spider>
	<spider ident="Araneo">
		<name>Araneo</name>
		<url>http://www.robotstxt.org/db/araneo.html</url>
	</spider>
	<spider ident="ArchitextSpider">
		<name>ArchitextSpider</name>
		<url>http://www.robotstxt.org/db/architext.html</url>
	</spider>
	<spider ident="archive.org_bot">
		<name>Archive.org</name>
		<url>https://archive.org/details/archive.org_bot</url>
	</spider>
	<spider ident="arks/1.0">
		<name>arks</name>
		<url>http://www.robotstxt.org/db/arks.html</url>
	</spider>
	<spider ident="ASpider">
		<name>ASpider</name>
		<url>http://www.robotstxt.org/db/aspider.html</url>
	</spider>
	<spider ident="ATN_Worldwide">
		<name>ATN Worldwide</name>
		<url>http://www.robotstxt.org/db/atn.html</url>
	</spider>
	<spider ident="Atomz">
		<name>Atomz.com</name>
		<url>http://www.robotstxt.org/db/atomz.html</url>
	</spider>
	<spider ident="AURESYS">
		<name>AURESYS</name>
		<url>http://www.robotstxt.org/db/auresys.html</url>
	</spider>
	<spider ident="AwarioSmartBot">
		<name>AwarioSmartBot</name>
		<url>https://awario.com/bots.html</url>
	</spider>
	<spider ident="AwarioRssBot">
		<name>AwarioRssBot</name>
		<url>https://awario.com/bots.html</url>
	</spider>
	<spider ident="BackRub">
		<name>BackRub</name>
		<url>http://www.robotstxt.org/db/backrub.html</url>
	</spider>
	<spider ident="Baiduspider">
		<name>Baiduspider</name>
		<url>http://www.baidu.com/search/spider.htm</url>
	</spider>
	<spider ident="BecomeBot">
		<name>BecomeBot</name>
		<url>http://www.become.com/webmasters.html</url>
	</spider>
	<spider ident="Big Brother">
		<name>Big Brother</name>
		<url>http://www.robotstxt.org/db/bigbrother.html</url>
	</spider>
	<spider ident="BigmirSpider">
		<name>Bigmir</name>
		<url>http://www.bigmir.net/</url>
	</spider>
	<spider ident="bingbot">
		<name>Bing</name>
		<url>http://www.bing.com/bingbot.htm</url>
	</spider>
	<spider ident="Bitacle bot">
		<name>Bitacle</name>
		<url>http://bitacle.org/</url>
	</spider>
	<spider ident="BitBot">
		<name>BitBot</name>
		<url>https://bitbot.dev</url>
	</spider>
	<spider ident="Biz360 Spider">
		<name>Biz</name>
		<url>http://www.biz360.com</url>
	</spider>
	<spider ident="Bjaaland">
		<name>Bjaaland</name>
		<url>http://www.robotstxt.org/db/bjaaland.html</url>
	</spider>
	<spider ident="BlackWidow">
		<name>BlackWidow</name>
		<url>http://www.robotstxt.org/db/blackwidow.html</url>
	</spider>
	<spider ident="BLEXBot">
		<name>BLEXBot</name>
		<url>http://webmeup-crawler.com/</url>
	</spider>
	<spider ident="BlogCrawler by Xango">
		<name>BlogCrawler</name>
	</spider>
	<spider ident="blogdb">
		<name>BlogDb</name>
		<url>http://blogdb.jp</url>
	</spider>
	<spider ident="blog search engine by BlogFan.ORG">
		<name>BlogFan</name>
		<url>http://www.blogfan.org</url>
	</spider>
	<spider ident="Bloglines">
		<name>Bloglies</name>
		<url>http://www.bloglines.com</url>
	</spider>
	<spider ident="BlogPulse (ISSpider-3.0)">
		<name>BlogPulse</name>
	</spider>
	<spider ident="BlogSearch">
		<name>BlogSearch</name>
		<url>http://www.icerocket.com</url>
	</spider>
	<spider ident="BlogsNowBot">
		<name>BlogsNow</name>
		<url>http://www.blogsnow.com/</url>
	</spider>
	<spider ident="BlogStreetBot">
		<name>BlogStreetBot</name>
		<url>http://www.blogstreet.com/</url>
	</spider>
	<spider ident="Bulkfeeds">
		<name>BlogStreetBot</name>
		<url>http://bulkfeeds.net</url>
	</spider>
	<spider ident="BoardPulse">
		<name>BoardPulse</name>
		<url>http://www.boardpulse.com/</url>
	</spider>
	<spider ident="BoardReader">
		<name>BoardReader</name>
		<url>http://www.boardreader.com/aboutus.asp</url>
	</spider>
	<spider ident="BoardViewer">
		<name>BoardViewer</name>
		<url>http://www.boardviewer.com/</url>
	</spider>
	<spider ident="boitho.com-robot">
		<name>Boitho</name>
		<url>http://www.boitho.com/bot.html</url>
	</spider>
	<spider ident="borg-bot">
		<name>Borg-Bot</name>
		<url>http://www.robotstxt.org/db/borg-bot.html</url>
	</spider>
	<spider ident="BSpider">
		<name>BSpider</name>
		<url>http://www.robotstxt.org/db/bspider.html</url>
	</spider>
	<spider ident="BublupBot">
		<name>BublupBot</name>
		<url>https://www.bublup.com/bublup-bot.html</url>
	</spider>
	<spider ident="Buck/2.2">
		<name>Buck</name>
		<url>https://app.hypefactors.com/media-monitoring/about.html</url>
	</spider>
	<spider ident="Bytespider">
		<name>Bytespider</name>
		<url>https://www.bytedance.com/</url>
	</spider>
	<spider ident="CACTVS Chemistry Spider">
		<name>CACTVS Chemistry</name>
	</spider>
	<spider ident="Calif">
		<name>Calif</name>
	</spider>
	<spider ident="CaRP/3.6Evolution">
		<name>CaRP</name>
		<url>http://www.biz360.com</url>
	</spider>
	<spider ident="CensysInspect">
		<name>Censys</name>
		<url>https://about.censys.io/</url>
	</spider>
	<spider ident="Checkbot">
		<name>Checkbot</name>
	</spider>
	<spider ident="ChristCrawler.com">
		<name>ChristCrawler.com</name>
	</spider>
	<spider ident="www.cienciaficcion.net">
		<name>cIeNcIaFiCcIoN.nEt</name>
	</spider>
	<spider ident="Cincraw">
		<name>Cincraw</name>
		<url>http://cincrawdata.net/bot/</url>
	</spider>
	<spider ident="CipinetBot">
		<name>Cipinet</name>
		<url>http://www.cipinet.com/bot.html</url>
	</spider>
	<spider ident="CJNetworkQuality">
		<name>CJNetworkQuality</name>
		<url>http://www.cj.com/networkquality/</url>
	</spider>
	<spider ident="CMC/0.01">
		<name>CMC/0.01</name>
	</spider>
	<spider ident="ColdFusion">
		<name>ColdFusion</name>
	</spider>
	<spider ident="combine">
		<name>Combine System</name>
	</spider>
	<spider ident="Crawler (cometsearch@cometsystems.com)">
		<name>cometsystems.com</name>
	</spider>
	<spider ident="ComputingSite Robi/1.0">
		<name>ComputingSite Robi/1.0</name>
	</spider>
	<spider ident="conceptbot">
		<name>Conceptbot</name>
	</spider>
	<spider ident="Cookiebot">
		<name>Cookiebot</name>
		<url>https://www.cookiebot.com/</url>
	</spider>
	<spider ident="Cooby.de Crawler">
		<name>Cooby.de Crawler</name>
	</spider>
	<spider ident="CoolBot">
		<name>CoolBot</name>
	</spider>
	<spider ident="CriteoBot">
		<name>Criteo</name>
		<url>https://www.criteo.com/criteo-crawler/</url>
	</spider>
	<spider ident="Cusco">
		<name>Cusco</name>
	</spider>
	<spider ident="CyberSpyder">
		<name>CyberSpyder</name>
	</spider>
	<spider ident="DataForSeoBot">
		<name>DataForSEO</name>
		<url>https://dataforseo.com/dataforseo-bot</url>
	</spider>
	<spider ident="daypopbot">
		<name>daypop</name>
	</spider>
	<spider ident="DesertRealm.com">
		<name>Desert Realm</name>
	</spider>
	<spider ident="Deweb">
		<name>DeWeb(c)</name>
	</spider>
	<spider ident="Die Blinde Kuh">
		<name>Die Blinde Kuh</name>
		<url>http://www.robotstxt.org/db/blindekuh.html</url>
	</spider>
	<spider ident="dienstspider">
		<name>DienstSpider</name>
	</spider>
	<spider ident="Digger/1.0 JDK/1.3.0">
		<name>Digger</name>
	</spider>
	<spider ident="Digimarc WebReader">
		<name>Digimarc MarcSpider</name>
	</spider>
	<spider ident="Digimarc CGIReader">
		<name>Digimarc Marcspider/CGI</name>
	</spider>
	<spider ident="DIIbot">
		<name>Digital Integrity Robot</name>
	</spider>
	<spider ident="grabber">
		<name>Direct Hit Grabber</name>
	</spider>
	<spider ident="discobot">
		<name>Discovery</name>
		<url>http://discoveryengine.com/discobot.html</url>
	</spider>
	<spider ident="Discordbot">
		<name>Discord</name>
		<url>https://discordapp.com/</url>
	</spider>
	<spider ident="DNAbot/1.0">
		<name>DNAbot</name>
	</spider>
	<spider ident="Domains Project">
		<name>Domains Project</name>
		<url>https://domainsproject.org/</url>
	</spider>
	<spider ident="DotBot">
		<name>Moz DotBot</name>
		<url>http://www.opensiteexplorer.org/dotbot</url>
	</spider>
	<spider ident="DragonBot/1.0 libwww/5.0">
		<name>DragonBot</name>
	</spider>
	<spider ident="dragonmetrics">
