=== WoltLab/WCF/XSD/userGroupOption.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install, update or delete user group options. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	 <!-- include option types -->
	<xs:include schemaLocation="optionTypes.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		 <xs:all>
			<xs:element name="categories" type="categories_import" minOccurs="0" />
			<xs:element name="options" type="options_import" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<!-- categories import element type -->
	<xs:complexType name="categories_import">
		<xs:sequence>
			<xs:element name="category" type="category_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated category element type -->
	<xs:complexType name="category_import">
		<xs:complexContent>
			<xs:extension base="category_delete">
				<xs:all>
					<xs:element name="parent" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="options" type="woltlab_varchar_nullable" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- options import element type -->
	<xs:complexType name="options_import">
		<xs:sequence>
			<xs:element name="option" type="option_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- imported/updated element type -->
	<xs:complexType name="option_import">
		<xs:complexContent>
			<xs:extension base="option_delete">
				<xs:all>
					<xs:element name="categoryname" type="woltlab_varchar" minOccurs="1" />
					<xs:element name="optiontype" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="defaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="userdefaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="moddefaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="validationpattern" type="xs:string" minOccurs="0" />
					<xs:element name="enableoptions" type="xs:string" minOccurs="0" />
					<xs:element name="showorder" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="options" type="xs:string" minOccurs="0" />
					<xs:element name="permissions" type="xs:string" minOccurs="0" />
					<xs:element name="admindefaultvalue" type="xs:string" minOccurs="0" />
					<xs:element name="usersonly" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="wildcard" type="woltlab_varchar_nullable" minOccurs="0" />
					<xs:element name="minvalue" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="maxvalue" type="xs:unsignedInt" minOccurs="0" />
					<xs:element name="excludedInTinyBuild" type="woltlab_boolean" minOccurs="0" />
					<xs:element name="suffix" type="woltlab_varchar" minOccurs="0" />
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== WoltLab/WCF/com.woltlab.wcf/userGroupOption.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/6.0/userGroupOption.xsd">
	<import>
		<categories>
			<category name="user"/>
			<category name="user.profile">
				<parent>user</parent>
			</category>
			<category name="user.profileComment">
				<parent>user.profile</parent>
			</category>
			<category name="user.signature">
				<parent>user.profile</parent>
			</category>
			<category name="user.profile.avatar">
				<parent>user.profile</parent>
			</category>
			<category name="user.profile.coverPhoto">
				<parent>user.profile</parent>
			</category>
			<category name="user.profile.trophy">
				<parent>user.profile</parent>
			</category>
			<category name="user.profile.payment">
				<parent>user.profile</parent>
			</category>
			<category name="user.message">
				<parent>user</parent>
			</category>
			<category name="user.like">
				<parent>user.message</parent>
			</category>
			<category name="user.message.attachment">
				<parent>user.message</parent>
			</category>
			<category name="user.message.comment">
				<parent>user.message</parent>
			</category>
			<category name="user.message.contactForm">
				<parent>user.message</parent>
			</category>
			<category name="user.message.poll">
				<parent>user.message</parent>
				<options>module_poll</options>
			</category>
			<category name="user.cms">
				<parent>user</parent>
			</category>
			<category name="user.article">
				<parent>user.cms</parent>
			</category>
			<category name="user.page">
				<parent>user.cms</parent>
			</category>
			<category name="mod"/>
			<category name="mod.general">
				<parent>mod</parent>
			</category>
			<category name="mod.profileComment">
				<parent>mod.general</parent>
			</category>
			<category name="mod.cms">
				<parent>mod</parent>
			</category>
			<category name="mod.page">
				<parent>mod.cms</parent>
			</category>
			<category name="mod.article">
				<parent>mod.cms</parent>
			</category>
			<category name="mod.poll">
				<parent>mod.general</parent>
				<options>module_poll</options>
			</category>
			<category name="admin"/>
			<category name="admin.general">
				<parent>admin</parent>
			</category>
			<!-- admin.configuration -->
			<category name="admin.configuration">
				<parent>admin</parent>
			</category>
			<category name="admin.configuration.package">
				<parent>admin.configuration</parent>
			</category>
			<!-- /admin.configuration -->
			<!-- admin.user -->
			<category name="admin.user">
				<parent>admin</parent>
			</category>
			<category name="admin.user.user">
				<parent>admin.user</parent>
			</category>
			<category name="admin.user.group">
				<parent>admin.user</parent>
			</category>
			<category name="admin.user.trophy">
				<parent>admin.user</parent>
			</category>
			<!-- /admin.user -->
			<!-- admin.content -->
			<category name="admin.content">
				<parent>admin</parent>
			</category>
			<!-- /admin.content -->
			<!-- admin.application -->
			<category name="admin.application">
				<parent>admin</parent>
			</category>
			<!-- /admin.application -->
			<!-- admin.customization -->
			<category name="admin.customization">
				<parent>admin</parent>
			</category>
			<!-- /admin.customization -->
			<!-- admin.management -->
			<category name="admin.management">
				<parent>admin</parent>
			</category>
		</categories>
		<options>
			<!-- admin.general -->
			<option name="admin.general.canViewPrivateUserOptions">
				<categoryname>admin.general</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.general.canViewPageDuringOfflineMode">
				<categoryname>admin.general</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canViewInvisible">
				<categoryname>admin.general</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canViewIpAddress">
				<categoryname>admin.general</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<!-- /admin.general -->
			<!-- admin.configuration -->
			<option name="admin.configuration.canEditOption">
				<categoryname>admin.configuration</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canEditActivityPoints">
				<categoryname>admin.configuration</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.captcha.canManageCaptchaQuestion">
				<categoryname>admin.configuration</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.contact.canManageContactForm">
				<categoryname>admin.configuration</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<options>module_contact_form</options>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.configuration.canManageApplication">
				<categoryname>admin.configuration.package</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.configuration.package.canUpdatePackage">
				<categoryname>admin.configuration.package</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.configuration.package.canEditServer">
				<categoryname>admin.configuration.package</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<!-- /admin.configuration -->
			<!-- admin.user -->
			<option name="admin.user.accessibleGroups">
				<categoryname>admin.user.group</categoryname>
				<optiontype>userGroups</optiontype>
				<admindefaultvalue>1,2,3,4,5</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canAddUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canSearchUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canEditUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canEditMailAddress">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canEditPassword">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canDeleteUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canEnableUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canBanUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canDisableAvatar">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canDisableSignature">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<options>module_user_signature</options>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canDisableCoverPhoto">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canMailUser">
				<categoryname>admin.user.user</categoryname>
				<optiontype>boolean</optiontype>
				<defaultvalue>0</defaultvalue>
				<admindefaultvalue>1</admindefaultvalue>
				<usersonly>1</usersonly>
			</option>
			<option name="admin.user.canManageNotificationSettings">
